[package]
name = "bevy-h3-globe"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
h3ron = "0.13.0"
h3ron-h3-sys = "0.12.0"
libh3 = "0.1.8"
map_3d = "0.1.4"
rand = "0.8.4"
bevy_fly_camera = "0.7.0"